### PR TITLE
feat: add NAF1 & NAF2

### LINKED ISSUE #48: feat: add NAF1, NAF2, NAF1-NAF2 concordance, NAF2-NACE2 concordance
## Description
brought to attention with the French corporate registry NAF version inconsistency issue

https://graph.internal.sayari.com/resource/entity/XaKzHirJ3qD7MMYzFqgAGg?activeattr=business_purpose&relationshipfield=has_shareholder&tab=attributes

## Environment
* OS
* Python version
* Package version

## Details
If necessary, describe the problem you have been experiencing in more detail.

## Code To Reproduce
If reporting a defect, please include a code sample to reproduce the defect and outline the expected behavior.

### PR DESCRIPTION
**Pull request by JSPromisel**
## Description
Adding NAF1 and NAF2 standards.

Closes #48 

## Types of changes

What types of changes does your code introduce:
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by maddyobrienjones — APPROVED** [review]
looks good! thanks for taking this on. since we're adding more NACE2 concordances lately, seems like we could add a `ToNACE2` composed graph to the main init file but maybe that should be a separate PR

**Comment by JSPromisel** [comment]
> looks good! thanks for taking this on. since we're adding more NACE2 concordances lately, seems like we could add a `ToNACE2` composed graph to the main init file but maybe that should be a separate PR

That would be a separate PR IMO. Is there a specific need for that functionality?

**Comment by maddyobrienjones** [comment]
> > looks good! thanks for taking this on. since we're adding more NACE2 concordances lately, seems like we could add a `ToNACE2` composed graph to the main init file but maybe that should be a separate PR
> 
> That would be a separate PR IMO. Is there a specific need for that functionality?

nah, just thought of it since the business purpose conversion allows for it because jordan requested the ability to do things other than `ToISIC4`

**Comment by JSPromisel** [comment]
> > > looks good! thanks for taking this on. since we're adding more NACE2 concordances lately, seems like we could add a `ToNACE2` composed graph to the main init file but maybe that should be a separate PR
> > 
> > 
> > That would be a separate PR IMO. Is there a specific need for that functionality?
> 
> nah, just thought of it since the business purpose conversion allows for it because jordan requested the ability to do things other than `ToISIC4`

Right, mind adding an issue for this to the backlog so we can discuss in backlog grooming?

**Pull request merged**
