### PR TITLE
feat(TOL2008): new standard

### LINKED ISSUE #82: feat(TOL2008): new standard
## Description
https://www2.stat.fi/en/luokitukset/toimiala/

## Environment
* OS
* Python version
* Package version

## Details
If necessary, describe the problem you have been experiencing in more detail.

## Code To Reproduce
If reporting a defect, please include a code sample to reproduce the defect and outline the expected behavior.

### PR DESCRIPTION
**Pull request by maddyobrienjones**
## Description
closes #82 

## Types of changes

What types of changes does your code introduce:
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by JSPromisel — APPROVED** [review]
Looks good thanks @maddyobrienjones

**Comment by maddyobrienjones** [comment]
@JSPromisel @nyoungstudios any thoughts on why the github actions aren't all running here?

**Comment by nyoungstudios** [comment]
Can you push another commit so that the workflow gets triggered again? I think it got stuck from the incident earlier today.

**Comment by maddyobrienjones** [comment]
@nyoungstudios ok will do. for the record, i haven't updated this since 4:30PM yesterday before the incident, and this has happened on previous PRs in this repo as well

**Comment by nyoungstudios** [comment]
Yea, I do see your initial commit without any GitHub action runs. I don't see any [incidents](https://www.githubstatus.com/history) for yesterday at the time. Last time, I remember the workflow was disabled since we had not contributed to this repo in a while and we had to click the enable button again. Not sure what the case was this time (I didn't click any enable button this time).

A side note, we should probably consider updating the GitHub action workflows in this repo to fix all the [warning messages](https://github.com/sayari-analytics/pyisic/actions/runs/9179998044?pr=83) and split out the separate jobs similar to many of our workflows are structured our other repos.

**Review by nyoungstudios — APPROVED** [review]
So, that you can merge/Jake doesn't need to review again.

**Pull request merged**
