### PR TITLE
feat: SKD/SKIS

### LINKED ISSUE #40: feat: Slovenian classification codes
## Description
Briefly describe the issue you are experiencing or the feature you want to see added.
Add classification mappings for:

- SKD – Standard Classification of Activities
- SKIS – Standard Classification of Institutional Sectors

See this [link](https://www.stat.si/statweb/en/methods/classifications)

## Environment
* OS
* Python version
* Package version

## Details
If necessary, describe the problem you have been experiencing in more detail.

## Code To Reproduce
If reporting a defect, please include a code sample to reproduce the defect and outline the expected behavior.

### PR DESCRIPTION
**Pull request by JSPromisel**
## Description
Adding two new classifications from Slovenia, see https://www.stat.si/statweb/en/methods/classifications

Closes #40 

## Types of changes

What types of changes does your code introduce:
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by maddyobrienjones — COMMENTED** [review]
seems fine to me, but i'm wondering if this is the best place to add in the SKIS codes, since they don't have a concordance with any of the existing standards, and from a quick look seem to be more related to company types than to industrial classifications. it seems like if we wanted to use these in the parser, we should just add those codes in sayari-graph somewhere rather than adding them to this library. interested in yours and jordan's thoughts on this though

**Comment by JSPromisel** [comment]
> seems fine to me, but i'm wondering if this is the best place to add in the SKIS codes, since they don't have a concordance with any of the existing standards, and from a quick look seem to be more related to company types than to industrial classifications. it seems like if we wanted to use these in the parser, we should just add those codes in sayari-graph somewhere rather than adding them to this library. interested in yours and jordan's thoughts on this though

I could go either way, they are a documented standard and formatted similarly to other standards, but without concordance and with more broad categories, perhaps it doesn't add much to `pyisic` functionality.

**Comment by maddyobrienjones** [comment]
> > seems fine to me, but i'm wondering if this is the best place to add in the SKIS codes, since they don't have a concordance with any of the existing standards, and from a quick look seem to be more related to company types than to industrial classifications. it seems like if we wanted to use these in the parser, we should just add those codes in sayari-graph somewhere rather than adding them to this library. interested in yours and jordan's thoughts on this though
> 
> I could go either way, they are a documented standard and formatted similarly to other standards, but without concordance and with more broad categories, perhaps it doesn't add much to `pyisic` functionality.

yeah fair enough. also meant to add to my comment, you should probably specify which skd standard this is (2002 vs 2008)

**Review by jvani — CHANGES_REQUESTED** [review]
> yeah fair enough. also meant to add to my comment, you should probably specify which skd standard this is (2002 vs 2008)

I agree with Maddy version for both standards.

Separately, I'm ok adding both SKIS and SKD.

**Review by maddyobrienjones — COMMENTED** [review]
i don't want to create a ton of more work for you but should we be adding the 2008 version as welll since that's the latest version? looks like there's a concordance table with SKD2002. which version does SVN/corporate_registry use (i would assume the latest one)? otherwise, looks good.

**Comment by JSPromisel** [comment]
@maddyobrienjones added skd2008 along with skd2002_to_skd2008 concordance.

**Review by maddyobrienjones — APPROVED** [review]
looks great to me. thanks for adding in SKD2008.

**Review by jvani — APPROVED** [review]

**Pull request merged**
